import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const repoRoot = process.cwd();

describe("app identity metadata", () => {
  it("uses What Can We Sing metadata instead of Next.js placeholders", () => {
    const layout = readFileSync(join(repoRoot, "app/layout.tsx"), "utf8");

    expect(layout).toContain("What Can We Sing");
    expect(layout).toContain("%s |");
    expect(layout).toContain(
      "Help a pickup quartet quickly find songs everyone can sing together right now."
    );
    expect(layout).not.toContain("Create Next App");
    expect(layout).not.toContain("Generated by create next app");
  });

  it("commits branded icon assets and removes the default favicon", () => {
    expect(existsSync(join(repoRoot, "app/favicon.ico"))).toBe(false);
    expect(existsSync(join(repoRoot, "public/icons/icon.svg"))).toBe(true);
    expect(existsSync(join(repoRoot, "public/icons/icon-192.svg"))).toBe(true);
    expect(existsSync(join(repoRoot, "public/icons/icon-512.svg"))).toBe(true);
    expect(existsSync(join(repoRoot, "public/icons/apple-touch-icon.svg"))).toBe(
      true
    );
  });
});
